version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-hook-form
    versions:
    - 6.14.2
    - 6.15.1
    - 6.15.2
    - 6.15.3
    - 6.15.4
    - 6.15.5
    - 7.0.0
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.6
    - 7.0.7
    - 7.1.0
    - 7.2.1
    - 7.2.3
  - dependency-name: netlify-cms-app
    versions:
    - 2.14.14
    - 2.14.17
    - 2.14.18
    - 2.14.20
    - 2.14.21
    - 2.14.22
    - 2.14.23
    - 2.14.24
    - 2.14.25
    - 2.14.26
    - 2.14.27
    - 2.14.29
    - 2.14.30
    - 2.14.32
    - 2.14.33
    - 2.14.35
    - 2.14.37
    - 2.14.38
    - 2.14.39
    - 2.14.40
    - 2.14.41
    - 2.14.44
    - 2.14.45
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.13.3
    - 2.13.4
    - 2.14.0
    - 2.14.1
    - 2.14.2
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.10.1
    - 3.9.0
  - dependency-name: gatsby-remark-images
    versions:
    - 3.10.0
    - 3.11.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.11.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.15.0
    - 2.16.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.11.0
